### ISSUE TITLE
Add information in README about versioning of Android Studio, build tools, Android version, etc

### ISSUE THREAD

**Issue by technoplato** [levibostian/AndroidBlanky#47]
<img width="608" alt="screen shot 2019-02-13 at 2 08 53 pm" src="https://user-images.githubusercontent.com/6922904/52740604-01e81700-2f99-11e9-917f-f261f73eb6b4.png">
<img width="747" alt="screen shot 2019-02-13 at 2 09 02 pm" src="https://user-images.githubusercontent.com/6922904/52740605-01e81700-2f99-11e9-90bd-59f9c25ac271.png">

Immediately after opening the project in the above listed version of Android Studio, I'm greeted with this message. We should add information regarding which versions of Android Studio, build tools, etc that this template uses.

**Comment by levibostian** [comment]
I am not sure this information is needed? If anyone wants to know the version of the build tools, it's located in `app/build.gradle` which is a default location. 

The readme does not include the version of Studio, sure. However, Studio does a fantastic job and being compatible with projects and makes it work. People should be able to use the project with whatever version of studio they wish to use IMO. 

Even though [this issue](https://github.com/levibostian/AndroidBlanky/issues/48) came up while updating, updating all of the dependencies to the new version fixed that issue.
