### ISSUE TITLE
some confusion about injection in the application?

### ISSUE THREAD

**Issue by gatspy** [levibostian/AndroidBlanky#79]
why `ReposTellerRepository` `ReposRepository` `UserManager`  and so on are not injecting dependencies in the `DependencyModule`?

**Comment by levibostian** [comment]
Hey there, @gatspy 

Are you asking if dependencies such as `UserManager` are inserted into the dependency graph of my app? 

You don't need to add dependencies to modules. You can also `@Inject` a constructor of your class:

```kotlin
class UserManager @Inject constructor(private val keyValueStorage: KeyValueStorage) {
                                 ^^^^^^
```

I only add classes to `DependencyModule` that are 3rd party dependencies that I can't use `@Inject` on. 

Does that answer your question?
